---
- name: Add a VMware vSwitch named same as student
  vmware_vswitch:
    hostname: '{{ deploy_vsphere_host }}'
    username: '{{ deploy_vsphere_user }}'
    password: '{{ deploy_vsphere_password }}'
    switch: "{{ student_name }}"
  delegate_to: localhost

# Deploy CSR1000v from a template using Ansible 'vmware_guest' module
- name: Deploy VM from template
  vmware_guest:
    hostname: '{{ deploy_vsphere_host }}'
    username: '{{ deploy_vsphere_user }}'
    password: '{{ deploy_vsphere_password }}'
    validate_certs: false
    datacenter: '{{ deploy_vsphere_datacenter }}'
    folder: '{{ deploy_vsphere_folder }}'
    name: '{{ item.rtr_name }}'
    annotation: "{{ item.notes }}"
    disk:
      - size_gb: '{{ guest_disk }}'
        type: thin
        datastore: '{{ deploy_vsphere_datastore }}'
    hardware:
      memory_mb: '{{ guest_memory }}'
      num_cpus: '{{ guest_vcpu }}'
    networks:
#      - name: '{{ port_group1 }}'
#      - name: '{{ port_group2 }}'
#      - name: '{{ port_group3 }}'
      - name: "{{ student_name }}"
      - name: "{{ student_name }}"
      - name: "{{ student_name }}"
    template: '{{ guest_template }}'
    wait_for_ip_address: false
  delegate_to: localhost
  loop: "{{ routers }}"

# Bootstrap CSR1000v using vApp properties rtr 3 and 4
- name: Update vApp Properties
  when: item.gi3_ip is not defined
  vmware_guest:
    hostname: '{{ deploy_vsphere_host }}'
    username: '{{ deploy_vsphere_user }}'
    password: '{{ deploy_vsphere_password }}'
    name: '{{ item.rtr_name }}'
    state: present
    validate_certs: false
    vapp_properties:
      - id: com.cisco.csr1000v.hostname.1
        type: string
        value: '{{ item.rtr_name }}'
      - id: com.cisco.csr1000v.domain-name.1
        type: string
        value: lab.local
      - id: com.cisco.csr1000v.login-username.1
        type: string
        value: '{{ guest_username }}'
      - id: com.cisco.csr1000v.login-password.1
        type: password
        value: '{{ guest_password }}'
      - id: com.cisco.csr1000v.privilege-password.1
        type: password
        value: '{{ guest_password }}'
      - id: com.cisco.csr1000v.license.1
        type: string
        value: ax
      - id: com.cisco.csr1000v.ios-config-0001.1
        type: string
        value: line vty 0 4
      - id: com.cisco.csr1000v.ios-config-0002.1
        type: string
        value: login local
      - id: com.cisco.csr1000v.ios-config-0003.1
        type: string
        value: transport input ssh
      - id: com.cisco.csr1000v.ios-config-0004.1
        type: string
        value: crypto key generate rsa modulus 4096
      - id: com.cisco.csr1000v.ios-config-0005.1
        type: string
        value: vrf definition mgmt-intf
      - id: com.cisco.csr1000v.ios-config-0006.1
        type: string
        value: address-family ipv4
      - id: com.cisco.csr1000v.ios-config-0007.1
        type: string
        value: interface GigabitEthernet1
      - id: com.cisco.csr1000v.ios-config-0008.1
        type: string
        value: vrf forwarding mgmt-intf
      - id: com.cisco.csr1000v.ios-config-0009.1
        type: string
        value: '{{ item.gi1_ip }}'
      - id: com.cisco.csr1000v.ios-config-0010.1
        type: string
        value: no shutdown
      - id: com.cisco.csr1000v.ios-config-0011.1
        type: string
        value: ' {{ router_gateway }}'
      - id: com.cisco.csr1000v.ios-config-0012.1
        type: string
        value: restconf
      - id: com.cisco.csr1000v.ios-config-0013.1
        type: string
        value: netconf ssh
      - id: com.cisco.csr1000v.ios-config-0014.1
        type: string
        value: netconf-yang
      - id: com.cisco.csr1000v.ios-config-0015.1
        type: string
        value: interface GigabitEthernet2
      - id: com.cisco.csr1000v.ios-config-0016.1
        type: string
        value: "ip address {{ item.gi2_ip }} 255.255.255.0"
      - id: com.cisco.csr1000v.ios-config-0017.1
        type: string
        value: no shutdown
      - id: com.cisco.csr1000v.ios-config-0018.1
        type: string
        value: interface GigabitEthernet1
      - id: com.cisco.csr1000v.ios-config-0019.1
        type: string
        value: "ip address {{ item.gi1_ip }} 255.255.255.0"
      - id: com.cisco.csr1000v.ios-config-0020.1
        type: string
        value: no shutdown
      - id: com.cisco.csr1000v.ios-config-0021.1
        type: string
        value: interface GigabitEthernet3
      - id: com.cisco.csr1000v.ios-config-0022.1
        type: string
        value: shutdown
# ospf config
      - id: com.cisco.csr1000v.ios-config-0023.1
        type: string
        value: router ospf 65535
      - id: com.cisco.csr1000v.ios-config-0024.1
        type: string
        value: network 10.96.0.0 0.7.255.255 area 0
      - id: com.cisco.csr1000v.ios-config-0025.1
        type: string
        value: redistribute connected subnets
      - id: com.cisco.csr1000v.ios-config-0026.1
        type: string
        value: do wr mem
  delegate_to: localhost
  loop: "{{ routers }}"

# Bootstrap CSR1000v using vApp properties rtr 1 and 2
- name: Update vApp Properties
  when: item.gi3_ip is defined
  vmware_guest:
    hostname: '{{ deploy_vsphere_host }}'
    username: '{{ deploy_vsphere_user }}'
    password: '{{ deploy_vsphere_password }}'
    name: '{{ item.rtr_name }}'
    state: present
    validate_certs: false
    vapp_properties:
      - id: com.cisco.csr1000v.hostname.1
        type: string
        value: '{{ item.rtr_name }}'
      - id: com.cisco.csr1000v.domain-name.1
        type: string
        value: lab.local
      - id: com.cisco.csr1000v.login-username.1
        type: string
        value: '{{ guest_username }}'
      - id: com.cisco.csr1000v.login-password.1
        type: password
        value: '{{ guest_password }}'
      - id: com.cisco.csr1000v.privilege-password.1
        type: password
        value: '{{ guest_password }}'
      - id: com.cisco.csr1000v.license.1
        type: string
        value: ax
      - id: com.cisco.csr1000v.ios-config-0001.1
        type: string
        value: line vty 0 4
      - id: com.cisco.csr1000v.ios-config-0002.1
        type: string
        value: login local
      - id: com.cisco.csr1000v.ios-config-0003.1
        type: string
        value: transport input ssh
      - id: com.cisco.csr1000v.ios-config-0004.1
        type: string
        value: crypto key generate rsa modulus 4096
      - id: com.cisco.csr1000v.ios-config-0005.1
        type: string
        value: vrf definition mgmt-intf
      - id: com.cisco.csr1000v.ios-config-0006.1
        type: string
        value: address-family ipv4
      - id: com.cisco.csr1000v.ios-config-0007.1
        type: string
        value: interface GigabitEthernet1
      - id: com.cisco.csr1000v.ios-config-0008.1
        type: string
        value: vrf forwarding mgmt-intf
      - id: com.cisco.csr1000v.ios-config-0009.1
        type: string
        value: '{{ item.gi1_ip }}'
      - id: com.cisco.csr1000v.ios-config-0010.1
        type: string
        value: no shutdown
      - id: com.cisco.csr1000v.ios-config-0011.1
        type: string
        value: ' {{ router_gateway }}'
      - id: com.cisco.csr1000v.ios-config-0012.1
        type: string
        value: restconf
      - id: com.cisco.csr1000v.ios-config-0013.1
        type: string
        value: netconf ssh
      - id: com.cisco.csr1000v.ios-config-0014.1
        type: string
        value: netconf-yang
      - id: com.cisco.csr1000v.ios-config-0015.1
        type: string
        value: interface GigabitEthernet2
      - id: com.cisco.csr1000v.ios-config-0016.1
        type: string
        value: "ip address {{ item.gi2_ip }} 255.255.255.0"
      - id: com.cisco.csr1000v.ios-config-0017.1
        type: string
        value: no shutdown
      - id: com.cisco.csr1000v.ios-config-0018.1
        type: string
        value: interface GigabitEthernet3
      - id: com.cisco.csr1000v.ios-config-0019.1
        type: string
        value: "ip address {{ item.gi3_ip }} 255.255.255.0"
      - id: com.cisco.csr1000v.ios-config-0020.1
        type: string
        value: no shutdown
      - id: com.cisco.csr1000v.ios-config-0021.1
        type: string
        value: interface GigabitEthernet1
      - id: com.cisco.csr1000v.ios-config-0022.1
        type: string
        value: "ip address {{ item.gi1_ip }} 255.255.255.0"
      - id: com.cisco.csr1000v.ios-config-0023.1
        type: string
        value: no shutdown
# ospf config
      - id: com.cisco.csr1000v.ios-config-0024.1
        type: string
        value: router ospf 65535
      - id: com.cisco.csr1000v.ios-config-0025.1
        type: string
        value: network 10.96.0.0 0.7.255.255 area 0
      - id: com.cisco.csr1000v.ios-config-0026.1
        type: string
        value: network 10.200.200.0 0.0.0.255 area 0
      - id: com.cisco.csr1000v.ios-config-0027.1
        type: string
        value: redistribute connected subnets
      - id: com.cisco.csr1000v.ios-config-0028.1
        type: string
        value: do wr mem

  delegate_to: localhost
  loop: "{{ routers }}"

# Power on CSR1000v
- name: Set the state of a virtual machine to poweron
  vmware_guest_powerstate:
    hostname: "{{ deploy_vsphere_host }}"
    username: "{{ deploy_vsphere_user }}"
    password: "{{ deploy_vsphere_password }}"
    validate_certs: false
    folder: "/{{ deploy_vsphere_datacenter }}/{{ deploy_vsphere_folder }}"
    name: "{{ item.rtr_name }}"
    state: powered-on
  delegate_to: localhost
  register: deploy
  loop: "{{ routers }}"
